export const lightTheme = {
  page__background: '#f5f5f5',
  page__background_linear_gradient:
    'linear-gradient(45deg, #f5f5f5 0%, #b5b5b5 50%, #f5f5f5 100% );',

  text_primary: '#2b2b2b',
  text_secondary: '#555555',
  text_error: '#d80000',
  text_primary_background: '#c2c2c2',
  text_shadow: '2px 2px #e0dfdf',
  link_color: '#107ae4',
  link_color_hover: '#44d075',

  card__background: '#fefefe',
  card__border: '#000000',
  card__background__shadow: '#2f2f2f',
  card__background__text__hover: '#56c47d',
  card__button__text: '#ffffff',
  card__button__text__hover: '#56c47d',
  card__background__link: '#0070b8',
  card__background__link__hover: '#56c47d',

  navbar_color_background: '#4c4c4c',
  navbar__button_color_text: '#4c4c4c',
  navbar__button_color_background: '#f5f5f5',
  navbar__button_color_background__hover: '#36ad60',
  navbar__button_color_background__active: '#44d075',
  navbar__tooltip_color_text: '#ffffff',
  navbar__tooltip_color_background: '#4c4c4c',

  homePage__hero__intro_box_color_text: '#000000',
  homePage__hero__intro_box_color_aplhabet__first_word: '#36ad60',
  homePage__hero__intro_box_color_aplhabet__second_word: '#b80000',
  homePage__hero__know_button__background: '#36ad60',
  homePage__hero__know_button__text: '#ffffff',
  homePage__hero__know_button__text__hover: '#2b2b2b',
  homePage__hero__know_button__border: '#36ad60',
  homePage__hero__know_button__border__hover: '#2b2b2b',
  homePage__contact_button__background: '#36ad60',
  homePage__contact_button__text: '#090909',
  homePage__contact_button__text__hover: '#ffffff',
  homePage__contact_button__border: '#36ad60',
  homePage__contact_button__border__hover: '#2b2b2b',

  aboutPage__table_color_background: '#f2f2f2',
  aboutPage__table_color_border: '#d3d3d3',
  aboutPage__table_color_headline: '#0070b8',
  aboutPage__table_color_text: '#3d3d3d',

  portfolioPage__nav_text: '#3d3d3d',
  portfolioPage__nav_text__hover: '#36ad60',
  portfolioPage__nav_text__active: '#0070b8',
  portfolioPage__nav_decoration: '#b2b2b2',

  contactPage__form_background: '#ffffff',
  contactPage__form_shadow: '#d9d9d9',
  contactPage__form_border: '#c2c2c2',
  contactPage__form_label__text: '#3d3d3d',
  contactPage__form_input__background: '#f2f2f2',
  contactPage__form_button__background: '#36d352',
  contactPage__form_button__background__hover: '#0d7433',
  contactPage__form_button__text: '#ffffff',
}

export const darkTheme = {
  page__background: '#252525',
  page__background_linear_gradient:
    'linear-gradient(45deg,#181818 0%,  #474747 50%,    #181818 100% );',

  text_primary: '#ffffff',
  text_secondary: '#ffffff',
  text_error: '#f40b0b',
  text_primary_background: '#000000',
  text_shadow: '2px 2px  #000453',
  link_color: '#ffbb66',
  link_color_hover: '#05cd48',

  card__background: '#565656ea',
  card__background__hover: '#3f3e3e',
  card__background__shadow: '#4f4e4e',
  card__border: '#000000',
  card__button__text: '#ffffff',
  card__button__text__hover: '#05cd48',
  card__background__link: '#c76e01',
  card__background__link__hover: '#05cd48',

  navbar_color_background: '#525151',
  navbar__button_color_text: '#f7f7f7',
  navbar__button_color_background: '#cac8c8',
  navbar__button_color_background__active: '#ffbb66',
  navbar__button_color_background__hover: '#00ff00',
  navbar__tooltip_color_text: '#f7f7f7',
  navbar__tooltip_color_background: '#343333',

  homePage__hero__intro_box_color_text: '#f7f7f7',
  homePage__hero__intro_box_color_aplhabet__first_word: '#00ff00',
  homePage__hero__intro_box_color_aplhabet__second_word: '#ff0b1f',

  homePage__hero__know_button__background: '#00ff00',
  homePage__hero__know_button__text: '#252525',
  homePage__hero__know_button__text__hover: '#ffffff',
  homePage__hero__know_button__border: '#000000',
  homePage__hero__know_button__border__hover: '#ffffff',

  homePage__contact_button__background: '#00ff00',
  homePage__contact_button__text: '#f5f2f2',
  homePage__contact_button__text__hover: '#343434',
  homePage__contact_button__border: '#ffffff',
  homePage__contact_button__border__hover: '#f7f7f7',

  aboutPage__table_color_background: '#595959',
  aboutPage__table_color_border: '#a7a5a5',
  aboutPage__table_color_headline: '#ffbb66',
  aboutPage__table_color_text: '#dddddd',

  portfolioPage__nav_text: '#cac8c8',
  portfolioPage__nav_text__hover: '#08d352',
  portfolioPage__nav_text__active: '#ffbb66',
  portfolioPage__nav_decoration: '#c2c2c2',

  contactPage__form_background: 'transparent',
  contactPage__form_shadow: 'transparent',
  contactPage__form_border: '#2b8e00',
  contactPage__form_label__text: '#ffffff',
  contactPage__form_input__background: '#edeaea',
  contactPage__form_button__background: '#08d352',
  contactPage__form_button__background__hover: '#0d7433',
  contactPage__form_button__text: '#340d0d',
}
